### ISSUE TITLE
请问可以设置固定采样率进行播放吗？

### ISSUE THREAD

**Issue by neo1201** [wanliyang1990/wlmusic#10]
请教大神一个问题：

在我进行音乐文件播放的时候可以设置固定采样率进行播放吗，er不是以音频原文件的采样率进行播放。
因为我需要将音频作为背景音乐进行录音，在混音(麦克风和背景音乐混合)的时候，希望在获取音频播放的pcm数据是和录音的采样率保持一致？
对音频这块还不是很了解，不知道我这种做法是不是正确的。

谢谢

**Comment by ywl5320** [comment]
可以 后面我把录音和固定频率功能给加上

**Comment by neo1201** [comment]
嗯，谢谢大神，如果可以的话，能不能先加一下那个固定频率播放的功能，混合录音的功能是公司其它同事用C++做的，我找了很多播放器好像很少有把pcm格式的数据返回给上层的。

**Comment by ywl5320** [comment]
好的

**Comment by ywl5320** [comment]
恒定采样率设置已经加了，你试试

**Comment by neo1201** [comment]
嗯嗯，好的，我试了，可以用，拜谢大神哈
