### ISSUE TITLE
请问同时只能播放一首歌曲吗？

### ISSUE THREAD

**Issue by neo1201** [wanliyang1990/wlmusic#11]
`WlMusic.getInstance();`
获取的是相同的实例，如果我想同时播放两首歌，分别获取各自音乐文件解码的pcm数据，这种情况可以吗？

**Comment by ywl5320** [comment]
恩 现在是这样的 只能播放一个音频文件

**Comment by longer96** [comment]
+1  希望能够同时播放多个音频， 这样可以同时听见多个大自然的声音啦~

**Comment by ywl5320** [comment]
嗯 现在正在重构代码 后面会把同时播放多个url功能加上 然后会加上视频播放功能 用于播放mv等视频

**Comment by ywl5320** [comment]
这个库已经加上了同时播放多个音频实例：https://github.com/wanliyang1990/wlmedia
