### ISSUE TITLE
播放完成回调

### ISSUE THREAD

**Issue by liuwei1225** [wanliyang1990/wlmusic#12]
这边播放完成回调中判断是否已经完成播放,WlMusic.getInstance().isPlaying()返回true,建议在onCallComplete的方法中将stop方法优先执行

**Comment by ywl5320** [comment]
好的 重构的新版中 会改正

**Comment by ywl5320** [comment]
新版本已经优化了 播放完成、播放出错等回调逻辑：https://github.com/wanliyang1990/wlmedia
