### ISSUE TITLE
 java.lang.UnsatisfiedLinkError

### ISSUE THREAD

**Issue by yanchunlan** [wanliyang1990/wlmusic#14]
java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.example.gl.opengles_demo-2/base.apk"],nativeLibraryDirectories=[/data/app/com.example.gl.opengles_demo-2/lib/arm64, /data/app/com.example.gl.opengles_demo-2/base.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64]]] couldn't find "libavutil-55.so"

**Comment by ywl5320** [comment]
仔细看readme，里面有配置的：
defaultConfig {
	...
	ndk {
	    abiFilter("armeabi-v7a")
	    abiFilter("x86")
	}

    }
