### ISSUE TITLE
录制音量变化和添加音效

### ISSUE THREAD

**Issue by CHG-SunySan** [wanliyang1990/wlmusic#15]

**Comment by CHG-SunySan** [comment]
在播放音乐的时候，可能会手动去控制音量的大小，此时我想音乐的音量大小声直接被录制进去，然后在播放录制的音乐的时候，会随着当时播放的音量大小声做对应的调整，这个可以做到吗？同时录制音乐过程中怎么录入其他音效的效果。

**Comment by ywl5320** [comment]
都可以做到 你可以自己在回调里面处理pcm数据 实现自己的效果

**Comment by CHG-SunySan** [comment]
也就是这个OnShowPcmDataListener的回调里面做对应的操作对吧？不过我现在还不懂怎么去处理pcm数据，特别是要知道音量大小是在哪个位置大声哪个位置小声，这个可以提示下怎么做操作吗，谢谢

**Comment by ywl5320** [comment]
pcm音量大小就是改嘛音频振幅值的大小，对应byte数据就是改变byte的值大小

**Comment by CHG-SunySan** [comment]
这个pcm数据是可以处理，但怎么知道它是在几秒的时间大声，几秒的时间点又是小声呢，有没有这个调控音量的时间点的回调呢

**Comment by ywl5320** [comment]
这样 那我还是在底层做吧 不过我不会在这个库上面改了 会在新的库https://github.com/wanliyang1990/wlmedia 上面更改

**Comment by CHG-SunySan** [comment]
好的 期待

**Comment by CHG-SunySan** [comment]
> 这样 那我还是在底层做吧 不过我不会在这个库上面改了 会在新的库https://github.com/wanliyang1990/wlmedia 上面更改

我看了下你那边的视频内容，发现里面也只有播录介绍，有时间可以讲解下播录同时麦克风录制吗

**Comment by ywl5320** [comment]
麦克风录制在推流的课程里面讲了的 只是麦克风和原有的音频混音没讲 但是这个也比较简单 直接相加就可以混音了 策略有很多种
