### ISSUE TITLE
是否可以播放服务端推送的流媒体数据吗？

### ISSUE THREAD

**Issue by qshnqjitx** [wanliyang1990/wlmusic#16]
是否可以播放服务端推送的流媒体数据吗？谢谢

**Comment by ywl5320** [comment]
如果是推送的rtmp、rtsp、http等流是可以播放的，如果是UDP等方式推送的buffer，这个库不支持，可以尝试用这个库：https://github.com/wanliyang1990/wlmedia

**Comment by qshnqjitx** [comment]
> wlmedia

wlmedia也是直接使用OpenSL ES播放音频吗？谢谢

**Comment by ywl5320** [comment]
音频 视频 都可以播放
