### ISSUE TITLE
可独立设置音量大小？

### ISSUE THREAD

**Issue by oudengding** [wanliyang1990/wlmusic#21]
哪里可以独立设置音量大小？能通过系统音量设置音量大小吗？

**Comment by ywl5320** [comment]
setVolume就可以独立设置音量大小哈，建议用：https://github.com/wanliyang1990/wlmedia 这个库，稳定性更好

**Comment by oudengding** [comment]
我的意思是有没有什么方法或者思路，能将当前系统播放音量设置为音频的音量
我是这里有个调节音频音量的功能，需要将在同一个手机音量等级下，调整后的音量播放的声音跟大一些




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"ywl5320"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月12日(星期四) 上午9:26
收件人:&nbsp;"wanliyang1990/wlmusic"<wlmusic@noreply.github.com&gt;;
抄送:&nbsp;"欧÷杀手"<2843901270@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [wanliyang1990/wlmusic] 可独立设置音量大小？ (#21)





 
setVolume就可以独立设置音量大小哈，建议用：https://github.com/wanliyang1990/wlmedia 这个库，稳定性更好

**Comment by oudengding** [comment]
大概就是关于ffmpeg 混音的问题。怎么控制每个音频的音量大小

**Comment by ywl5320** [comment]
你到底是怎样的场景，怎么又和混音扯到一起了呢？
播放器现在的逻辑是：默认情况下，播放的音频是最大音量，其次通过控制系统音量是可以改变大小的。（比如：播放器设置为50%的音量，那么系统音量开到最大也只有音频源50%的音量大小）

**Comment by oudengding** [comment]
我想实现这个图片上的功能，调整后可直接试听， 不知道你有没有什么思路？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"ywl5320"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月12日(星期四) 上午9:56
收件人:&nbsp;"wanliyang1990/wlmusic"<wlmusic@noreply.github.com&gt;;
抄送:&nbsp;"欧÷杀手"<2843901270@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [wanliyang1990/wlmusic] 可独立设置音量大小？ (#21)





 
你到底是怎样的场景，怎么又和混音扯到一起了呢？
 播放器现在的逻辑是：默认情况下，播放的音频是最大音量，其次通过控制系统音量是可以改变大小的。（比如：播放器设置为50%的音量，那么系统音量开到最大也只有音频源50%的音量大小）

**Comment by ywl5320** [comment]
没看到图片呢

**Comment by oudengding** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"ywl5320"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月12日(星期四) 上午10:06
收件人:&nbsp;"wanliyang1990/wlmusic"<wlmusic@noreply.github.com&gt;;
抄送:&nbsp;"欧÷杀手"<2843901270@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [wanliyang1990/wlmusic] 可独立设置音量大小？ (#21)





 
没看到图片呢

**Comment by ywl5320** [comment]
没有看到。。。

**Comment by oudengding** [comment]
老哥，能加一下我的QQ吗？
2843901270




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"ywl5320"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月12日(星期四) 上午10:11
收件人:&nbsp;"wanliyang1990/wlmusic"<wlmusic@noreply.github.com&gt;;
抄送:&nbsp;"欧÷杀手"<2843901270@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [wanliyang1990/wlmusic] 可独立设置音量大小？ (#21)





 
没有看到。。。
