### ISSUE TITLE
录制完成后无法播放sd卡

### ISSUE THREAD

**Issue by Victory-Over** [wanliyang1990/wlmusic#24]
在SD卡找了 只有路径 没有找到录制的aac文件
请问下是什么问题
![image](https://user-images.githubusercontent.com/15376263/85382570-ad33b380-b571-11ea-9a60-c3d13fd32907.png)

![image](https://user-images.githubusercontent.com/15376263/85382603-b45ac180-b571-11ea-8995-129b42795fa8.png)

**Comment by Victory-Over** [comment]
wlMusic.stopRecordPlaying();
是不是只需要调用这句代码 就代表录制完成了

**Comment by ywl5320** [comment]
看样子是创建文件失败了的，你的手机系统版本是多少呢 android 10存储卡是沙盒模式了

**Comment by Victory-Over** [comment]
确实是Android10，
![image](https://user-images.githubusercontent.com/15376263/85495440-1583a300-b60d-11ea-9cda-f6314b1e67d6.png)
我采用这种方式获取目录也创建不了文件

**Comment by ywl5320** [comment]
你把targetSdkVersion改成29以下 试一下

**Comment by Victory-Over** [comment]
![image](https://user-images.githubusercontent.com/15376263/85497569-bcb60980-b610-11ea-9265-f531fc8e546a.png)
一样的，应该是Android10 手机问题

**Comment by Victory-Over** [comment]
![image](https://user-images.githubusercontent.com/15376263/85497598-c7709e80-b610-11ea-9be2-780403277562.png)

**Comment by ywl5320** [comment]
恩 你只有去看沙盒模式下 怎么创建文件了

**Comment by Victory-Over** [comment]
![image](https://user-images.githubusercontent.com/15376263/85505159-47523500-b620-11ea-8939-f374438566fb.png)
我这边断点看你源码创建文件夹是没问题的
到了最后一行创建文件的时候应该失败了，
但是我看不到更里面的源码

**Comment by ywl5320** [comment]
你最好把对应的文件夹层级先用java创建好，底层直接创建文件就可以了（自动创建）。
