### ISSUE TITLE
音乐播放加载链接失败，就一直加载，有什么失败的回调，或者其他方法可以播放下一首

### ISSUE THREAD

**Issue by momeak123123** [wanliyang1990/wlmusic#25]

**Comment by ywl5320** [comment]
不是有error回调吗

**Comment by momeak123123** [comment]
> 不是有错误一点吗

没反应，他在setOnLoadListener()返回true之后，就没了

**Comment by ywl5320** [comment]
那你迁移到这个库吧：https://github.com/wanliyang1990/wlmedia 这个库更完善

**Comment by momeak123123** [comment]
> 那你迁移到这个库吧：https://github.com/wanliyang1990/wlmedia 这个库更完善

好,我看看

**Comment by ywl5320** [comment]
恩 wlmedia使用有什么问题 直接可以问我哈
