### ISSUE TITLE
amr文件获取不到duration

### ISSUE THREAD

**Issue by ggoyea** [wanliyang1990/wlmusic#26]
如题

**Comment by ywl5320** [comment]
能给个测试地址或文件不呢 我试试

**Comment by ggoyea** [comment]
[ed7e941a1e43431dad5c974c82589e95.zip](https://github.com/wanliyang1990/wlmusic/files/4856417/ed7e941a1e43431dad5c974c82589e95.zip)

**Comment by ywl5320** [comment]
用这个库 https://github.com/wanliyang1990/wlmedia 替换wlmusic就可以了
