### ISSUE TITLE
还有怎么播放本地文件？还有个raw里面的声音

### ISSUE THREAD

**Issue by 287138531** [wanliyang1990/wlmusic#3]
还有怎么播放本地文件？还有个raw里面的声音

**Comment by ywl5320** [comment]
本地文件直接传入文件路径就可以了；要播放raw里面的声音，需要把raw里面的音频文件拷贝到本地存储卡里就可以了，然后就和播放本地文件一样。

**Comment by 287138531** [comment]
最好能支持raw和assts，这个是集成在app内部的声效。。

**Comment by ywl5320** [comment]
后续添加相应的功能

**Comment by ywl5320** [comment]
raw和assets播放工具类添加了，具体用法看readme文档
