### ISSUE TITLE
循环播放没有声音

### ISSUE THREAD

**Issue by 287138531** [wanliyang1990/wlmusic#4]
1.setOnErrorListener没有回调
2.声音文件为15s左右的mp3
3.关掉循环播放，就正常了

另外需要一个  mediaPlayer.isPlaying()这样判断是否在播放的方法。麻烦了

**Comment by ywl5320** [comment]
都没有回调还是在某一情况下没有回调
然后给我一个短音频我测试一下呢

**Comment by 287138531** [comment]
我的意思是貌似没有报错（setOnErrorListener没有回调），就是听不到声音，加个qq吧 287138531

**Comment by ywl5320** [comment]
好 加你了
