### ISSUE TITLE
音频是不是不支持https

### ISSUE THREAD

**Issue by maxiaoxu2017** [wanliyang1990/wlmusic#7]
集成后https地址的音频播放不出来，http的正常，是不是不支持https？

**Comment by ywl5320** [comment]
恩 现在还没有添加https支持，你可以给我一个测试的地址，我下个版本加上

**Comment by maxiaoxu2017** [comment]
@wanliyang1990 
非常感谢！
以下是测试用https的音频地址：
https://tests001.pnlyy.com/Fn57-AhK0RjfjymvEoIErGKmmcPm
https://vips-static.pnlyy.com/Fn57-AhK0RjfjymvEoIErGKmmcPm

**Comment by ywl5320** [comment]
已经加了https支持了哈 你试试
