### ISSUE TITLE
播放本地音频出错了

### ISSUE THREAD

**Issue by neo1201** [wanliyang1990/wlmusic#9]
![image](https://user-images.githubusercontent.com/5358278/46934209-76fa1d00-d089-11e8-84b4-317219154cca.png)

文件放在assets目录了，
```
  String url = RawAssetsUtil.getAssetsFilePath(this, "test.mp3");
        wlMusic.setSource(url);
        wlMusic.prePared();
```
`setOnErrorListener ` 没有日志输出

**Comment by ywl5320** [comment]
这些可以忽略，是可以播放的

**Comment by neo1201** [comment]
嗯嗯，不好意思，我弄错了，把文件放到demo中可以播放
